[versions]

kotlin = 				        "2.2.10"
kotlinx-serialization-json =    "1.6.0"

[plugins]

kotlin-serialization = 			    { id = "org.jetbrains.kotlin.plugin.serialization",         version.ref = "kotlin" }
kotlin-jvm =                        { id = "org.jetbrains.kotlin.jvm",                          version.ref = "kotlin" }

[libraries]

kotlinx-serialization-json =         { module = "org.jetbrains.kotlinx:kotlinx-serialization-json",    version.ref = "kotlinx-serialization-json" }

